# Generated by Django 5.0.1 on 2024-01-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
    ]
